### ISSUE TITLE
FLOP counts off by factor of 10?

### ISSUE THREAD

**Issue by Lamikins** [facebookresearch/DiT#14]
Great work,

in the original GPT-3 paper the authors report 6 forward FLOPs / param / token for their GPT models.

Since DiT is effectively the same architecture as GPT, why are the DiT flops ~9-10x fewer than GPT?

For example, a 650M GPT-3 model with seqlen=256 has (650e6 * 6 * 256) / 1e9 ~= 1 TFLOPS forward,
Whereas for a DiT of the same size & sequence length this is 118 GFLOPS reported in the paper.

What am I missing?

**Comment by wpeebles** [comment]
Hi @Lamikins, good question. My understanding is that the the 6*NT formula (where N=parameters, T=tokens) applies to combined forward + backward flops. For most figures in our paper (except Fig 8), we are counting only forward flops, so the more applicable formula is 2*NT since the backward pass is approximated as taking 2x the flops of forward. Another thing to keep in mind is that we use the representation learning literature's convention of counting flops effectively as MACs (i.e., each multiply-add is 1 flop), so another factor of 2 should be removed from the equation leaving 1*NT. Finally, the adaLN-Zero modules add a lot of parameters but very few flops to DiT. Removing those parameters leaves ~449M pure-transformer params in DiT-XL/2, and the formula gives NT = 449M * 256 / 1e9 = ~110 Gflops, which is close to the number we calculated.

**Comment by Lamikins** [comment]
Thanks!

**Comment by dszpr** [comment]
mark

**Comment by yiakwy-xpu-ml-framework-team** [comment]
It is just rough estimation (with references 6NT formula without visiting the real structure of model layers after layers) of generation of image (only fwd) in terms of MACs.
